---
title: "Fig.S2_Ternary plot of field survey"
author: "Huanhuan Zhu"
date: "2025-09-29"
output: html_document
---


## Fig.S2a_Ternary plot prokaryotes
```{r, fig.align='center', fig.height=10, fig.width=12, warning=FALSE, message=FALSE}

#############################Fig.S2_Ternary plot of field survey ##########################

library(dplyr)
library(tibble)
library(indicspecies)
#library(scatterpie)
library(ggtern) # ggplot2 version musct <= 3.5.2
library(patchwork)

#Bacteria
rm(list = ls())

setwd("E:/Functrait/Result/Bacteria/otu2") 

otu_all0 <- read.csv("otu_bacteriaFlattening_rrncor.csv", check.names = F, row.names = 1, header = T) 
otu_all0 <- as.data.frame(t(otu_all0))
otu_all0 <- otu_all0[!grepl("S14", rownames(otu_all0)), ]


bacteria_group <- read.csv("E:/Functrait/Result/metadata/metadata.csv", header = T)
rownames(bacteria_group) <- bacteria_group$runningSampleID

bacteria_group <- bacteria_group[rownames(otu_all0),]

table(rownames(bacteria_group) == rownames(otu_all0))

# 

# set.seed(123)
# indicator_results <- multipatt(otu_all0,
#                                bacteria_group$type,
#                                func = "IndVal",
#                                control = how(nperm = 100))

# saveRDS(indicator_results,"ternary plot/indicator_results_species.rds")
indicator_results <- readRDS("ternary plot/indicator_results_species.rds")


significant_indicators <- indicator_results$sign
significant_matrix <- as.data.frame(significant_indicators[which(significant_indicators$p.value < 0.05), ]) # 

p_adj <- data.frame(p.adjust(significant_matrix$p.value, method = "fdr"))
table(p_adj[,1] < 0.05)

# three abundance
otu_all1 <- merge(otu_all0, bacteria_group, by = "row.names", all = TRUE)


otu_all1 <- otu_all1[,c(colnames(otu_all0),"type")]


otu_all1 <- otu_all1 %>%
  group_by(type) %>%
  summarise(across(everything(), sum))

otu_all1 <- column_to_rownames(otu_all1, "type")
otu_all2 <- as.data.frame(t(otu_all1))

otu_all2 <- as.data.frame(apply(otu_all2, 2, function(x) x / sum(x)))
otu_all2 <- otu_all2[rownames(significant_matrix),]

otu_all2 <- merge(otu_all2, significant_matrix, by = "row.names", all = TRUE)

bac_info <- read.csv("FUNTRAIT.bact.OTU.ID1.csv")

otu_all2 <- merge(otu_all2, bac_info, by.x = "Row.names", by.y = "OTU.ID", all.x = TRUE)


# all abundance 
all_abundance <- as.data.frame(colSums(otu_all1))
colnames(all_abundance) <- "reads"
all_abundance$OTU.ID <- rownames(all_abundance)
all_abundance$reads <- (as.numeric(all_abundance$reads) / sum(as.numeric(all_abundance$reads))) * 100


otu_all2 <- merge(otu_all2, all_abundance, by.x = "Row.names", by.y = "OTU.ID", all.x = TRUE)
otu_all3 <- otu_all2[otu_all2$index < 4, ]

order_phylum <- as.data.frame(table(otu_all2$V5_02))
order_phylum <- order_phylum[order(order_phylum$Freq, decreasing = T),]

otu_all2[!(otu_all2$V5_02 %in% order_phylum$Var1[1:10]),]$V5_02 = "Others"


colors <- c(
  "#E41A1C", # red
  "#0000FF", # pink
  "#FF7F00", # orange
  "#984EA3", # purple
  "black", # green
  "#377EB8", # blue
  "#A65628", # dark brown
  "#FFFF33", # yellow
  "#1B9E77", # dark teal
  "#D95F02", # deep orange
  "#666666" # gray
)


Froot_tern <- ggtern(otu_all2[otu_all2$index < 4, ], aes(Z, B, W, color = factor(V5_02, levels = rev(c(as.character(order_phylum$Var1[1:10]),"Others"))))) +
  geom_mask() +
  geom_point(aes(size = reads, shape = factor(index)), alpha = 0.8) +
  #scale_alpha_manual(values = c( 0, 0.8)) +
  scale_color_manual(name = "Phylum", values = rev(colors), guide = guide_legend(order = 1,
                                                                            override.aes = list(size=6))) +
  scale_shape_manual(name = "Indicator", values = c( 15,16, 17), labels=c( "3" = "Rhizosphere", 
                                                                           "1" = "Maizebulk", 
                                                                           "2" = "Wildland"),
                     guide = guide_legend(order = 2,
                                          override.aes = list(size=6))) +
  scale_size_continuous(name = "Relative abundance (%)", range = c(1.5, 3),guide = guide_legend(order = 3)) +
  #theme_showarrows() +
  theme_bw() +
  labs(title = "Indicative prokaryotic OTUs", 
       y = "Rhizosphere",
       x = "Maizebulk",
       z = "Wildland") +
  theme(
        legend.position = "right",
        plot.title = element_text(color="black", size=30,hjust=0.5),
        axis.title = element_blank(), 
        tern.axis.title.L = element_text(size=26, color = "black",hjust = 0,vjust=2.5),
        tern.axis.title.R = element_text(size=26, color = "black",hjust = 1, vjust=2.5),
        tern.axis.title.T = element_text(size=26, color = "black", hjust = 0.5, vjust=0),
        axis.text = element_text(size=22, color="black"),
        legend.title = element_text(size=26, color = "black"),
        legend.text = element_text(size = 22, color = "black")) 

Froot_tern

# pie plot
pie_df <- as.data.frame(table(otu_all3$V5_02, otu_all3$index))
pie_df$Var1 <- as.character(pie_df$Var1)
pie_df[!(pie_df$Var1 %in% as.character(order_phylum$Var1[1:10])),]$Var1 = "Others"

pie_df <- aggregate(.~Var1 + Var2, pie_df, FUN = "sum")

df_summary <- pie_df %>%
  group_by(Var2) %>%
  summarise(total = sum(Freq, na.rm = TRUE))
df_summary

pie_df_pct <- pie_df %>%
  group_by(Var2) %>%
  mutate(Percent = Freq / sum(Freq) * 100) %>%
  ungroup()

pie_df_pct$Var2 <- factor(pie_df_pct$Var2 , levels = c(3,1,2))
pie_df_pct$Var1 <- factor(pie_df_pct$Var1 , levels = c(as.character(order_phylum$Var1[1:10]),"Others"))

p_all <- ggplot(pie_df_pct, aes(x = "", y = Percent, fill = Var1)) +
  geom_bar(stat = "identity", width = 0.1,alpha = 0.7) +
  coord_polar(theta = "y", clip = "off") +
  facet_wrap(~Var2, nrow = 1, labeller = as_labeller(c(
    `1` = "Maizebulk\n(n = 205)",
    `2` = "Wildland\n(n = 3810)",
    `3` = "Rhizosphere\n(n = 267)"
  ))) +
  scale_fill_manual(values = colors) +
  theme_void() +
  theme(
    plot.margin = margin(0,120,0,120),
    strip.text = element_text(size = 26, vjust = -40), 
    panel.spacing = unit(0, "cm"), 
    legend.position = "none",                          
    legend.key.height = unit(0.4,"cm"),
    legend.key.width = unit(0.5,"cm"),
    legend.background = element_blank()
  )


p_final <- ((Froot_tern + theme(plot.margin = margin(0,0,0,0), plot.title = element_text(vjust=-1)))/plot_spacer()/p_all + plot_layout(guides = "collect", heights = c(10,-1.5,4))) +
  theme(plot.margin = margin(0,0,40,0))

print(p_final)

#1200 1000
```


## Fig.S2b_Ternary plot fungi
```{r, fig.align='center', fig.height=10, fig.width=12, warning=FALSE, message=FALSE}

rm(list = ls())

setwd("E:/Functrait/Result/Fungi/otu2")

otu_all0 <- read.csv("otu_fungFlattening_rrncor.csv", check.names = F, row.names = 1, header = T)
otu_all0 <- as.data.frame(t(otu_all0))
otu_all0 <- otu_all0[!grepl("S14", rownames(otu_all0)), ]


fungi_group <- read.csv("E:/Functrait/Result/metadata/metadata.csv", header = T)
rownames(fungi_group) <- fungi_group$runningSampleID

fungi_group <- fungi_group[rownames(otu_all0),]

table(rownames(fungi_group) == rownames(otu_all0))

# set.seed(123)
# indicator_results <- multipatt(otu_all0, 
#                                fungi_group$type, 
#                                func = "IndVal", 
#                                control = how(nperm = 100))
# 
# saveRDS(indicator_results,"ternary plot/indicator_results_species_fung.rds")
indicator_results <- readRDS("ternary plot/indicator_results_species_fung.rds")

significant_indicators <- indicator_results$sign
significant_matrix <- as.data.frame(significant_indicators[which(significant_indicators$p.value < 0.05), ])

# three abundance
otu_all1 <- merge(otu_all0, fungi_group, by = "row.names", all = TRUE)

otu_all1 <- otu_all1[,c(colnames(otu_all0),"type")]
library(dplyr)
library(tibble)

otu_all1 <- otu_all1 %>%
  group_by(type) %>%
  summarise(across(everything(), sum))

otu_all1 <- column_to_rownames(otu_all1, "type")
otu_all2 <- as.data.frame(t(otu_all1))

otu_all2 <- as.data.frame(apply(otu_all2, 2, function(x) x / sum(x)))
otu_all2 <- otu_all2[rownames(significant_matrix),]

otu_all2 <- merge(otu_all2, significant_matrix, by = "row.names", all = TRUE)

fung_info <- read.csv("FUNTRAIT.fung.OTU.ID1.csv")

otu_all2 <- merge(otu_all2, fung_info, by.x = "Row.names", by.y = "OTU.ID", all.x = TRUE)


# all abundance 
all_abundance <- as.data.frame(colSums(otu_all1))
colnames(all_abundance) <- "reads"
all_abundance$OTU.ID <- rownames(all_abundance)
all_abundance$reads <- (as.numeric(all_abundance$reads) / sum(as.numeric(all_abundance$reads))) * 100


otu_all2 <- merge(otu_all2, all_abundance, by.x = "Row.names", by.y = "OTU.ID", all.x = TRUE)
otu_all3 <- otu_all2[otu_all2$index < 4, ]

order_phylum <- as.data.frame(table(otu_all2$V5_3))
order_phylum <- order_phylum[order(order_phylum$Freq, decreasing = T),]

otu_all2[!(otu_all2$V5_3 %in% order_phylum$Var1[1:10]),]$V5_3 = "Others"


colors <- c(
  "#E41A1C", # red
  "#0000FF", # pink
  "#FF7F00", # orange
  "#984EA3", # purple
  "black", # green
  "#377EB8", # blue
  "#A65628", # dark brown
  "#FFFF33", # yellow
  "#1B9E77", # dark teal
  "#D95F02", # deep orange
  "#666666" # gray
  
)


Froot_tern <- ggtern(otu_all2[otu_all2$index < 4, ], aes(Z, B, W, color = factor(gsub("^c__", "",V5_3), levels = rev(c(gsub("^c__", "",as.character(order_phylum$Var1[1:10])),"Others"))))) +
  geom_mask() +
  geom_point(aes(size = reads, shape = factor(index)), alpha = 0.8) +
  #scale_alpha_manual(values = c( 0, 0.8)) +
  scale_color_manual(name = "Class", values = rev(colors), guide = guide_legend(order = 1,
                                                                                 override.aes = list(size=6))) +
  scale_shape_manual(name = "Indicator", values = c( 15,16, 17), labels=c( "3" = "Rhizosphere", 
                                                                           "1" = "Maizebulk", 
                                                                           "2" = "Wildland"),
                     guide = guide_legend(order = 2,
                                          override.aes = list(size=6))) +
  scale_size_continuous(name = "Relative abundance (%)", range = c(1.5, 3),guide = guide_legend(order = 3)) +
  #theme_showarrows() + 
  theme_bw() +
  labs(title = "Indicative fungal OTUs", 
       y = "Rhizosphere",
       x = "Maizebulk",
       z = "Wildland") +
  theme(
    legend.position = "right",
    plot.title = element_text(color="black", size=30,hjust=0.5),
    axis.title = element_blank(),
    tern.axis.title.L = element_text(size=26, color = "black",hjust = 0,vjust=2.5),
    tern.axis.title.R = element_text(size=26, color = "black",hjust = 1, vjust=2.5),
    tern.axis.title.T = element_text(size=26, color = "black", hjust = 0.5, vjust=0),
    axis.text = element_text(size=22, color="black"),
    legend.title = element_text(size=26, color = "black"),
    legend.text = element_text(size = 22, color = "black")) 

Froot_tern

# pie plot
pie_df <- as.data.frame(table(otu_all3$V5_3, otu_all3$index))
pie_df$Var1 <- as.character(pie_df$Var1)
pie_df[!(pie_df$Var1 %in% as.character(order_phylum$Var1[1:10])),]$Var1 = "Others"

pie_df <- aggregate(.~Var1 + Var2, pie_df, FUN = "sum")

df_summary <- pie_df %>%
  group_by(Var2) %>%
  summarise(total = sum(Freq, na.rm = TRUE))
df_summary

pie_df_pct <- pie_df %>%
  group_by(Var2) %>%
  mutate(Percent = Freq / sum(Freq) * 100) %>%
  ungroup()

pie_df_pct$Var2 <- factor(pie_df_pct$Var2 , levels = c(3,1,2))
pie_df_pct$Var1 <- factor(pie_df_pct$Var1 , levels = c(as.character(order_phylum$Var1[1:10]),"Others"))

p_all <- ggplot(pie_df_pct, aes(x = "", y = Percent, fill = Var1)) +
  geom_bar(stat = "identity", width = 0.1,alpha = 0.7) +
  coord_polar(theta = "y", clip = "off") +
  facet_wrap(~Var2, nrow = 1, labeller = as_labeller(c(
    `1` = "Maizebulk\n(n = 75)",
    `2` = "Wildland\n(n = 490)",
    `3` = "Rhizosphere\n(n = 27)"
  ))) +
  scale_fill_manual(values = colors) +
  theme_void() +
  theme(
    plot.margin = margin(0,120,0,120),
    strip.text = element_text(size = 26, vjust = -40), 
    panel.spacing = unit(0, "cm"), 
    legend.position = "none",                          
    legend.key.height = unit(0.4,"cm"),
    legend.key.width = unit(0.5,"cm"),
    legend.background = element_blank()
  )


p_final <- ((Froot_tern + theme(plot.margin = margin(0,0,0,0), plot.title = element_text(vjust=-1)))/plot_spacer()/p_all + plot_layout(guides = "collect", heights = c(10,-1.5,4))) +
  theme(plot.margin = margin(0,0,40,0))

print(p_final)

### 1200 1000

```
