---
title: "Fig.1a & Fig.4a_mapCN with aridity"
author: "Huanhuan Zhu"
date: "2025-09-19"
output: html_document
---



## Fig.1a_Field sampling map
```{r, fig.align='center', fig.height=7.5, fig.width=12.5, warning=FALSE, message=FALSE}

library(RColorBrewer)
library(cowplot)
library(colorRamps)
library(ggrepel)
library(sf)
library(ggspatial)
library(tidyterra)
library(ggnewscale)
library(terra)

rm(list=ls())

# aridity level of china
setwd("E:/Functrait/Result/site")

china <- st_read("China.json", quiet = TRUE)

ai <- rast("D:/ArcGIS-Data/7504448/Global-AI_ET0_v3_annual/ai_v3_yr.tif")

china_proj <- st_transform(china, crs(ai))
china_vect <- vect(china_proj)

ai_china <- crop(ai, china_vect)
ai_china_masked <- mask(ai_china, china_vect)

ai_china_masked <- 1- (ai_china_masked*0.0001)



breaks <- seq(-1, 1,by=0.5) 

colors <- adjustcolor(
  c(colorRampPalette(rev(c(
    "#BD0026", "#E31A1C", 
    "#FC4E2A", "#FD8D3C",
    "#FEB24C", "#FED976", 
    "#FFFFB2", "#FFFFCC",
    "#D9F0A3", "#ADDD8E", "#78C679", "#41AB5D",
    "#238443", "#006837", "#B2E2E2", "#66C2A4",
    "#41B6C4", "#2C7FB8", "#225EA8", "#253494",
    "#081D58"
  )))(41)),
  alpha.f = 0.75
)


# fileld samling map
site <- read.csv("site information.csv",header = T)
site.functraits <- read.csv("../metadata/metadata.csv")
site.functraits1 <- aggregate(.~site,site.functraits[,c("site", "longtitude", "latitude")], FUN = "mean")

site.functraits1 <- st_as_sf(site.functraits1,coords=c("longtitude","latitude"),crs=4326)
#site.functraits1$name <- "Survey sites"
#site.functraits1 <- site.functraits1[,2:3]

colors2 <- c(
  "#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00",
  "#FFFF33", "#A65628", "#F781BF", "#666666", "#1B9E77",
  "#D95F02", "#6495ED", "#E7298A", "#66A61E", "#A6761D",
  "#20B2AA", "#8B0000", "#FFD700", "#00CED1", "#8A2BE2",
  "#00FF7F", "#00BFFF", "#708090"
)

mapCN<-ggplot() + 
  geom_spatraster(data = ai_china_masked) +
  scale_fill_gradientn(
    colors = colors,
    na.value = "transparent",
    breaks = breaks,
    limits = range(breaks),
    oob = scales::squish,
    name = "Aridity",
    guide = guide_colorbar(
      barwidth = unit(0.4, "cm"),
      barheight = unit(3, "cm"),
    )
  ) +
  new_scale_fill() +
  geom_sf(data = china,fill="NA",color="black",size=0.3) + 
  #geom_sf(data = nine_line,color="black",size=0.5) + 
  scale_size(range = c(1,5))+
  annotation_scale(location = "bl",line_width = 2,text_cex = 1.5) +
  annotation_north_arrow(location = "tl", which_north = "true",
                         height = unit(2.5, "cm"), 
                         width = unit(2.5, "cm"),
                         style = north_arrow_fancy_orienteering)+
  geom_sf(data=site.functraits1,aes(fill=site),size=2, alpha=1, shape = 21)+
  #geom_text_repel(data = site_all,aes(label=name,geometry=geometry),stat = "sf_coordinates",color="blue",size=10)+
  #annotate("text",x=-2556175.2,y=-2387082,label="GS??(2022)1061??",size=3)+
  #scale_fill_manual(values= c("brown","blue"),name="Site")+
  scale_fill_manual(name="Site", values = colors2,guide = guide_legend(ncol = 1, override.aes = list(size = 4))) +
  guides(shape = guide_legend(override.aes = list(size = 6)))+
  coord_sf(ylim = c(-2387082,1654989),xlim = c(-2556175.2,2816095),crs = "+proj=laea +lat_0=40 +lon_0=104")+
  theme_bw()+xlab("Longitude")+ylab("Latitude")+
  theme(plot.margin=unit(c(0,0,0,0),"mm"),
        #legend.position = "none",
        #legend.position = c(0.9340, 0.7005), 
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 16), # ,margin = margin(t = 10,unit = "pt")
        legend.key.size = unit(1, "lines"),         # legend key height
        legend.spacing.y = unit(0.4,"cm"), 
        legend.background = element_rect(fill = NA, color = NA),
        legend.box.background = element_rect(fill = NA, color = NA, size = 0.1),
        axis.text = element_text(size = 20,colour = "black",face = "bold"),
        #axis.title = element_text(size = 20,colour = "black",face = "bold"),
        axis.title = element_blank())

mapCN_nineline<-ggplot() + 
  geom_spatraster(data = ai_china_masked) +
  scale_fill_gradientn(
    colors = colors,
    na.value = "transparent",
    breaks = breaks,
    limits = range(breaks),
    oob = scales::squish,
    name = "Aridity"
  ) +
  geom_sf(data = china,fill="NA",color="black",size=0.5) +
  scale_size(range = c(1,5))+
  annotation_scale(location = "br",line_width = 0.8,text_cex = 1) +
  coord_sf(ylim = c(-4228017,-1877844),xlim = c(117131.4,2115095),crs="+proj=laea +lat_0=40 +lon_0=104")+
  scale_x_continuous(breaks = c(105, 120))  +
  theme_bw()+
  theme(aspect.ratio = 1.5,
        axis.text = element_text(color="black", size=14), 
        plot.margin=unit(c(0,0,0,0),"mm"),
        legend.position = "none")

mapCN_all <- ggdraw()+
  draw_plot(mapCN)+
  draw_plot(mapCN_nineline,x = 0.710, y = 0.08, width = 0.14, height = 0.264)

p <- mapCN_all+theme(
  plot.margin = margin(t = 10, r = 10, b = 10, l = 10, unit = "pt")
)


print(p)

```


## Fig.4a_HMME Samling map
```{r, fig.align='center', fig.height=7.5, fig.width=12.5, warning=FALSE, message=FALSE}

# HMME sampling map
setwd("E:/Functrait/Result/site")
site <- read.csv("site information.csv",header = T)

site.HMME<-st_as_sf(site,coords=c("longitude","latitude"),crs=4326)
#site.HMME$name<- "Collecting sites"
site.HMME$name <- factor(site.HMME$name, levels=c("MY","LX","BT","DL"))

colors2 <- c(
  "#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00",
  "#FFFF33", "#A65628", "#F781BF", "#666666", "#1B9E77",
  "#D95F02", "#6495ED", "#E7298A", "#66A61E", "#A6761D",
  "#20B2AA", "#8B0000", "#FFD700", "#00CED1", "#8A2BE2",
  "#00FF7F", "#00BFFF", "#708090"
)

mapCN<-ggplot() + 
  geom_spatraster(data = ai_china_masked) +
  scale_fill_gradientn(
    colors = colors,
    na.value = "transparent",
    breaks = breaks,
    limits = range(breaks),
    oob = scales::squish,
    name = "Aridity",
    guide = guide_colorbar(
      barwidth = unit(0.5, "cm"), 
      barheight = unit(4, "cm"), 
    )
  ) +
  new_scale_fill() +
  geom_sf(data = china,fill="NA",color="black",size=0.3) + 
  #geom_sf(data = nine_line,color="black",size=0.5) + 
  scale_size(range = c(1,5))+
  annotation_scale(location = "bl",line_width = 2,text_cex = 2.5) +
  annotation_north_arrow(location = "tl", which_north = "true",
                         height = unit(3, "cm"), 
                         width = unit(3, "cm"),
                         style = north_arrow_fancy_orienteering)+
  geom_sf(data=site.HMME,size=8, alpha=1, aes(fill=name), shape = 21)+
  #geom_text_repel(data = site_all,aes(label=name,geometry=geometry),stat = "sf_coordinates",color="blue",size=10)+
  #annotate("text",x=-2556175.2,y=-2387082,label="GS??(2022)1061??",size=3)+
  #scale_fill_manual(values= c("brown","blue"),name="Site")+
  scale_fill_manual(name="Site", values = colors2, labels=c(
    'MY'="Mangya",
    'BT'="Baotou",
    'LX'="Longxi",
    "DL"="Duolun"
  )) +
  #guides(fill = guide_legend(order=2))+
  coord_sf(ylim = c(-2387082,1654989),xlim = c(-2556175.2,2816095),crs = "+proj=laea +lat_0=40 +lon_0=104")+
  theme_bw()+xlab("Longitude")+ylab("Latitude")+
  theme(plot.margin=unit(c(0,0,0,0),"mm"),
        #legend.position = "none",
        legend.title = element_text(size = 30),
        legend.key.size = unit(2, "lines"), 
        legend.spacing.y = unit(1,"cm"), 
        legend.text = element_text(size = 26), # ,margin = margin(t = 10,unit = "pt")
        axis.text = element_text(size = 26,colour = "black",face = "bold"),
        #axis.title = element_text(size = 20,colour = "black",face = "bold"),
        axis.title = element_blank())


mapCN_nineline<-ggplot() + 
  geom_spatraster(data = ai_china_masked) +
  scale_fill_gradientn(
    colors = colors,
    na.value = "transparent",
    breaks = breaks,
    limits = range(breaks),
    oob = scales::squish,
    name = "Aridity"
  ) +
  geom_sf(data = china,fill="NA",color="black",size=0.5) +
  scale_size(range = c(1,5))+
  annotation_scale(location = "br",line_width = 0.8,text_cex = 1) +
  coord_sf(ylim = c(-4228017,-1877844),xlim = c(117131.4,2115095),crs="+proj=laea +lat_0=40 +lon_0=104")+
  scale_x_continuous(breaks = c(105, 120))  +
  theme_bw()+
  theme(aspect.ratio = 1.5,
        axis.text = element_text(color="black", size=16), 
        plot.margin=unit(c(0,0,0,0),"mm"), 
        legend.position = "none")

mapCN_all <- ggdraw()+
  draw_plot(mapCN)+
  draw_plot(mapCN_nineline,x = 0.672, y = 0.08, width = 0.14, height = 0.264)

p <- mapCN_all+theme(
  plot.margin = margin(t = 10, r = 10, b = 10, l = 10, unit = "pt")
)

print(p)

```