---
title: "Fig.S3a & Fig.S3b_Pie and point plot of differential OTUs"
author: "Huanhuan Zhu"
date: "2025-10-09"
output: html_document
---


# Fig.S3a Prokaryotes
```{r, fig.align='center', fig.height=7.0, fig.width=19.5, warning=FALSE, message=FALSE}


#############################Fig.S3a & Fig.S3b_Pie and point plot of differential OTUs##########################

library(Maaslin2)
library(data.table)
library(tidyverse)
library(ggh4x)
library(ggplot2)
library(patchwork)
library(scatterpie)


rm(list=ls())

setwd("E:/Functrait/Result/Bacteria/otu2/")

otu_all0 <- as.data.frame(fread("otu_bacteriaFlattening_rrncor.csv"))
otu_all0 <- column_to_rownames(otu_all0,"V1")
otu_all0 <- as.data.frame(t(otu_all0))


otu_all0$runningSampleID <- rownames(otu_all0)

metadata <- read.csv("metadata.csv")

otu_all1 <- merge(otu_all0, metadata[,c("runningSampleID","ai2000","type")], by="runningSampleID")
otu_all1_z <- otu_all1[otu_all1$type=="Z",]
otu_all1_z$ai2000 <- 1-1/otu_all1_z$ai2000

otu_all1_z <- otu_all1_z[!grepl("S14", otu_all1_z$runningSampleID),]


rownames(otu_all1_z) <- NULL
otu_all1_z <- column_to_rownames(otu_all1_z,"runningSampleID")


metadata <-data.frame("id" = rownames(otu_all1_z), "ai2000" = otu_all1_z$ai2000) 
metadata <- column_to_rownames(metadata,"id")

fit_data <- Maaslin2(
  input_data = otu_all1_z[,1:16713],
  input_metadata = metadata,
  min_abundance = 0,
  min_prevalence = 0.01,
  min_variance = 0.0,
  output = "D:/Rtmp",
  normalization = "NONE",
  transform = "LOG",
  analysis_method = "LM",
  fixed_effects = c("ai2000"),
  random_effects = NULL,
  plot_scatter = FALSE
)
rp1 <- fit_data$results
colnames(rp1)[1] = "otu"

rp1$type <- "none"
rp1[rp1$coef > 0.00 & rp1$qval <0.05,]$type <- "Up"
rp1[rp1$coef <= 0.00 & rp1$qval <0.05,]$type <- "Down"
rp1[rp1$qval >= 0.05,]$type <- "Stable"


group <- read.csv("FUNTRAIT.bact.OTU.ID1.csv")
qiime2 <- read.csv("E:/Functrait/Result/Bacteria/qiime2/FUNTRAIT.bact.OTU.ID1.csv")
# 
# table(blast2$V1 %in% group$V1)

#saveRDS(blast2,"./hmsc/blast2.RDS")
blast2 <- readRDS("gtdb/blast_gtdb.RDS")
#blast2 <- blast2[blast2$V9 >70 & blast2$V12 >90,]
blast3 <- merge(blast2, group[, c("V1", "OTU.ID","V5_02")], by.x="Feature.ID", by.y="V1")
blast3 <- blast3[,c("OTU.ID", "V5_02", "genome_size")]


rp1 <- separate(rp1, otu, sep = "\\.", into = "otu")
blast3 <- separate(blast3, OTU.ID, sep = "\\.", into = "OTU.ID")

rp2 <- merge(rp1, blast3, by.x="otu", by.y="OTU.ID", all.y = TRUE)
rp2[is.na(rp2$type),]$type <- "Stable"


overzero <- as.data.frame(colSums(otu_all1_z[,1:16713]))
overzero$id <- rownames(overzero)
overzero <- separate(overzero, id, sep = "\\.", into = "id")
names(overzero)[1] = "abundance"

rp2 <- rp2[rp2$otu %in% overzero[overzero$abundance > 0, ]$id,]

pie_df <- as.data.frame(table(rp2$V5_02, rp2$type))
colnames(pie_df) <- c("OTU", "Type", "Count")
pie_df <- reshape(pie_df, idvar = "OTU", timevar = "Type", direction = "wide")



# second pie df
pie_abun <- as.data.frame(colSums(otu_all1_z[,1:(ncol(otu_all1_z)-2)]))
pie_abun$OTU <- sub("^(OTU[0-9]+).*", "\\1", rownames(pie_abun))
names(pie_abun)[1] = "abun"

rp2_pie_abun <- merge(pie_abun, rp2[,c("otu","type")], by.x="OTU", by.y="otu", all.x = T)
rp2_pie_abun2 <- merge(rp2_pie_abun, group[,c("V1","V5_02")], by.x="OTU", by.y="V1", all.x = T)
rp2_pie_abun2[is.na(rp2_pie_abun2$type),"type"] = "Stable"
rp2_pie_abun3 <- aggregate(abun ~ V5_02 + type, rp2_pie_abun2, FUN = "sum")


#pie_df$Non_significant <- rowSums(pie_df[, c("Count.Filtered", "Count.Stable")])


# phylum
#otu_all1_z1 <- as.data.frame(t(otu_all1_z[,rp1[rp1$type != "Stable",]$OTU.ID]))
otu_all1_z1 <- as.data.frame(t(otu_all1_z))
otu_all1_z1[] <- lapply(otu_all1_z1, as.numeric) 
otu_all1_z1$OTU.ID <- rownames(otu_all1_z1)

otu_all1_z1 <- merge(otu_all1_z1, group, by="OTU.ID", stringsAsFactors = FALSE)


otu_all1_z2 <- aggregate(.~V5_02, otu_all1_z1[,c(2:658,671)], FUN = "sum")
otu_all1_z2 <- column_to_rownames(otu_all1_z2, "V5_02")

otu_all1_z2 <- as.data.frame(t(otu_all1_z2))
otu_all1_z2 <- otu_all1_z2[rownames(metadata),]

fit_data2 <- Maaslin2(
  input_data = otu_all1_z2,
  input_metadata = metadata,
  min_abundance = 0.001,
  min_prevalence = 0.01,
  min_variance = 0.0,
  output = "D:/Rtmp",
  normalization = "NONE",
  transform = "LOG",
  analysis_method = "LM",
  fixed_effects = c("ai2000"),
  random_effects = NULL,
  plot_scatter = FALSE
)

rp1_1 <- fit_data2$results
colnames(rp1_1)[1] = "otu"

rp1_1$type <- "none"
rp1_1[rp1_1$coef > 0.00 & rp1_1$qval <0.05,]$type <- "Up"
rp1_1[rp1_1$coef <= 0.00 & rp1_1$qval <0.05,]$type <- "Down"
rp1_1[rp1_1$qval >= 0.05,]$type <- "Stable"

abundance <- as.data.frame(colSums(otu_all1_z2))
names(abundance) <- "abu"
abundance$otu <- rownames(abundance)
abundance$abu <- (abundance$abu/sum(abundance$abu))*100
abundance <- abundance[order(abundance$abu, decreasing = T),]

select_phy <- abundance[order(abundance$abu, decreasing = T),"otu"][1:15]

rp1_1 <- left_join(rp1_1, abundance, by = "otu") 
rp1_1 <- rp1_1[rp1_1$otu %in% select_phy,]



blast2 <- readRDS("gtdb/blast_gtdb.RDS")
#blast2 <- blast2[blast2$V9 >70 & blast2$V12 >90,]
blast3 <- merge(blast2, group[, c("V1", "OTU.ID","V5_02")], by.x="Feature.ID", by.y="V1")

gs <- aggregate(genome_size~V5_02, blast3, FUN = "mean")
gs_sd <- aggregate(genome_size~V5_02, blast3, FUN = "sd")
gs <- left_join(gs, gs_sd, by="V5_02")

gs <- gs[gs$V5_02 %in% select_phy,]
gs$label <- paste0(round(gs$genome_size.x/1000000,2), " ± ", round(gs$genome_size.y/1000000,2)," (Mb)")

gs <- left_join(gs, rp1_1, by=c("V5_02"="otu"))


diff_plot <- ggplot(rp1_1, aes(x=coef, y=factor(otu, levels = rev(c(select_phy))), size = abu, fill = factor(type, levels = c("Up","Down","Stable")))) +
  geom_point(shape=21) +
  geom_text(data = gs, aes(x=coef+0.4, y=V5_02, label =label), size=7.5, color="black") +
  scale_size_continuous(name="Phylum relative abundance (%)", range = c(3, 8)) +
  scale_fill_manual(name = "Phylum relative abundance", values = c("Down" = "#1445f8",
                                              "Up" = "#cd1936",
                                              "Stable" = "gray"),
                    labels =c("Up" = "Increase with aridity",
                              "Down" = "Decrease with aridity",
                              "Stable" = "Non-significant")) +
  guides(
    fill = guide_legend(
      override.aes = list(size = 6), order=1 # 图例点变大
    ),
    size = guide_legend(order = 2)
  ) +
  scale_x_continuous(breaks = c(-0.3, 0, 0.3, 0.6, 0.9), limits = c(-0.31,1)) +
  theme_bw() +
  labs(y="Top 15 phylum", x="MassLin2 coefficient") +
  theme(axis.title.x = element_text(size=26),
        axis.text.x = element_text(size=22, color = "black"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(size=26),
        legend.text = element_text(size=22),
        legend.box.margin=margin(l=20) # 控制图例之间的距离
        )

diff_plot


pie_df2 <- data.frame(
  "Phylum" = as.character(pie_df$OTU),
  "Up" = as.numeric(pie_df$Count.Up),
  "Down" = as.numeric(pie_df$Count.Down),
  "Stable" = as.numeric(pie_df$Count.Stable)
)

pie_df3 <- pie_df2[pie_df2$Phylum %in% select_phy,]
rownames(pie_df3) <- pie_df3$Phylum
pie_df3 <- pie_df3[rev(select_phy),]
pie_df3$x <- rep(1, nrow(pie_df3))  
pie_df3$y = 1:nrow(pie_df3)


pie_df3$all <- rowSums(pie_df3[,3:5])
pie_df3$Phylum2 <- paste0(pie_df3$Phylum, " (n = ",pie_df3$all,")")


pie_plot <- ggplot() +
  geom_scatterpie(data = pie_df3, aes(x = x, y = y, group=Phylum, r=0.4),
                  cols = c("Up", "Down", "Stable"), color = NA) +
  scale_fill_manual(name = "Accumulated OTU number", values = c("Down"="#2d9d56",
                               "Up"="#ff9d00",
                               "Stable"="gray"), 
                    labels =c("Up" = "Increase with aridity",
                              "Down" = "Decrease with aridity",
                              "Stable" = "Non-significant"))+
  scale_y_continuous(breaks = pie_df3$y, labels = pie_df3$Phylum2, expand = c(0.012, 0.012)) +  # 设置 y 轴的标签为 Phylum
  coord_equal() +
  labs(y="Top 15 phylum") +
  theme_void() +
  theme(axis.text.y = element_text(size=22, color = "black", hjust=1,  margin = margin(r = 10)),
        axis.title.y = element_text(size=26, angle = 90, margin = margin(r = 10)),
        legend.text = element_text(size=22),
        legend.title = element_text(size=26),
        legend.box.margin=margin(l=10) # 控制图例之间的距离
        )



pie_plot


# pie abundance
rp2_pie_abun4 <- rp2_pie_abun3 %>%
  pivot_wider(
    names_from = type,
    values_from = abun
  )

pie_df2_abundance <- data.frame(
  "Phylum" = as.character(rp2_pie_abun4$V5_02),
  "Up" = as.numeric(rp2_pie_abun4$Up),
  "Down" = as.numeric(rp2_pie_abun4$Down),
  "Stable" = as.numeric(rp2_pie_abun4$Stable)
)

pie_df3_abundance <- pie_df2_abundance[pie_df2_abundance$Phylum %in% select_phy,]
rownames(pie_df3_abundance) <- pie_df3_abundance$Phylum
pie_df3_abundance <- pie_df3_abundance[rev(select_phy),]
pie_df3_abundance$x <- rep(1, nrow(pie_df3_abundance))  
pie_df3_abundance$y = 1:nrow(pie_df3_abundance)

pie_plot_abun <- ggplot() +
  geom_scatterpie(data = pie_df3_abundance, aes(x = x, y = y, group=Phylum, r=0.4),
                  cols = c("Up", "Down", "Stable"), color = NA) +
  scale_fill_manual(name = "OTU counts", values = c("Down"="#2d9d56",
                                                   "Up"="#ff9d00",
                                                   "Stable"="gray"), 
                    labels =c("Up" = "Increase",
                              "Down" = "Decrease",
                              "Stable" = "Non-significant"))+
  scale_y_continuous(breaks = pie_df3$y, labels = pie_df3$Phylum2, expand = c(0.012, 0.012)) +  # 设置 y 轴的标签为 Phylum
  coord_equal() +
  labs(y="Top 15 phylum") +
  theme_void() +
  theme(axis.text.y = element_text(size=22, color = "black", hjust=1,  margin = margin(r = 10)),
        axis.title.y = element_text(size=26, angle = 90, margin = margin(r = 10)),
        legend.text = element_text(size=22),
        legend.title = element_text(size=26),
        legend.box.margin=margin(l=20) # 控制图例之间的距离
  )

pie_plot_abun


pie_plot_abun <- ggplot() +
  geom_scatterpie(data = pie_df3_abundance, aes(x = x, y = y, group=Phylum, r=0.4),
                  cols = c("Up", "Down", "Stable"), color = NA) +
  scale_fill_manual(name = "Accumulated OTU relative abundance", values = c("Down"="#9467BD",
                                                   "Up"="chocolate",
                                                   "Stable"="gray"), 
                    labels =c("Up" = "Increased with aridity",
                              "Down" = "Decrease with aridity",
                              "Stable" = "Non-significant"))+
  scale_y_continuous(breaks = pie_df3$y, labels = pie_df3$Phylum2, expand = c(0.012, 0.012)) +  # 设置 y 轴的标签为 Phylum
  coord_equal() +
  labs(y="Top 15 phylum") +
  theme_void() +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        legend.text = element_text(size=22),
        legend.title = element_text(size=26),
        legend.box.margin=margin(l=20) # 控制图例之间的距离
  )

pie_plot_abun


p <- (pie_plot|plot_spacer()|pie_plot_abun|plot_spacer()|diff_plot) + plot_layout(guides = "collect",widths = c(1, -0.95, 1,-0.48,1)) +
  ggtitle("Prokaryotes") +
  theme(plot.title = element_text(size=30, hjust = 0.5),
        legend.text = element_text(size=22),
        legend.title = element_text(size=26)
        )

print(p)
# 1950 700

```


# Fungi
```{r, fig.align='center', fig.height=7.0, fig.width=18.3, warning=FALSE, message=FALSE}

rm(list=ls())


setwd("E:/Functrait/Result/Fungi/otu2/")

otu_all0 <- as.data.frame(fread("otu_fungFlattening_rrncor.csv"))
otu_all0 <- column_to_rownames(otu_all0,"V1")
otu_all0 <- as.data.frame(t(otu_all0))


otu_all0$runningSampleID <- rownames(otu_all0)

metadata <- read.csv("metadata.csv")

otu_all1 <- merge(otu_all0, metadata[,c("runningSampleID","ai2000","type")], by="runningSampleID")
otu_all1_z <- otu_all1[otu_all1$type=="W",]
otu_all1_z$ai2000 <- 1-1/otu_all1_z$ai2000

otu_all1_z <- otu_all1_z[!grepl("S14", otu_all1_z$runningSampleID),]


rownames(otu_all1_z) <- NULL
otu_all1_z <- column_to_rownames(otu_all1_z,"runningSampleID")


metadata <-data.frame("id" = rownames(otu_all1_z), "ai2000" = otu_all1_z$ai2000) 
metadata <- column_to_rownames(metadata,"id")


fit_data <- Maaslin2(
  input_data = otu_all1_z[,1:(ncol(otu_all1_z)-2)],
  input_metadata = metadata,
  min_abundance = 0.001,
  min_prevalence = 0.01,
  min_variance = 0.0,
  output = "D:/Rtmp",
  normalization = "NONE",
  transform = "LOG",
  analysis_method = "LM",
  fixed_effects = c("ai2000"),
  random_effects = NULL,
  plot_scatter = FALSE
)
rp1 <- fit_data$results
colnames(rp1)[1] = "otu"



rp1$type <- "none"
rp1[rp1$coef > 0.00 & rp1$qval <0.05,]$type <- "Up"
rp1[rp1$coef <= 0.00 & rp1$qval <0.05,]$type <- "Down"
rp1[rp1$qval >= 0.05,]$type <- "Stable"



#saveRDS(blast2,"./hmsc/blast2.RDS")
otu_id_with_traits <- readRDS("traits/otu_id_with_traits.rds")


rp1 <- separate(rp1, otu, sep = "\\.", into = "otu")
otu_id_with_traits <- separate(otu_id_with_traits, OTU.ID, sep = "\\.", into = "OTU.ID")

rp1 <- merge(rp1, otu_id_with_traits, by.x="otu", by.y="OTU.ID", all.y = T)

rp1 <- separate(rp1, genus, sep = "_", into=c("pre_genus", "genus"))

rp2 <- rp1
rp2[is.na(rp2$type),]$type <- "Stable"


overzero <- as.data.frame(colSums(otu_all1_z[,1:(ncol(otu_all1_z)-2)]))
overzero$id <- rownames(overzero)
overzero <- separate(overzero, id, sep = "\\.", into = "id")
names(overzero)[1] = "abundance"

rp2 <- rp2[rp2$otu %in% overzero[overzero$abundance > 0, ]$id,]

pie_df <- as.data.frame(table(rp2$genus, rp2$type))
colnames(pie_df) <- c("OTU", "Type", "Count")
pie_df <- reshape(pie_df, idvar = "OTU", timevar = "Type", direction = "wide")

#pie_df$Non_significant <- rowSums(pie_df[, c("Count.Filtered", "Count.Stable")])

# second pie df
pie_abun <- as.data.frame(colSums(otu_all1_z[,1:(ncol(otu_all1_z)-2)]))
pie_abun$OTU <- sub("^(OTU[0-9]+).*", "\\1", rownames(pie_abun))  # \\1 只保留括号里的部分
names(pie_abun)[1] = "abun"

rp2_pie_abun <- merge(pie_abun, rp2[,c("otu","type")], by.x="OTU", by.y="otu", all.x = T)
rp2_pie_abun2 <- merge(rp2_pie_abun, otu_id_with_traits[,c("V1","genus")], by.x="OTU", by.y="V1", all.x = T)
rp2_pie_abun2[is.na(rp2_pie_abun2$type),"type"] = "Stable"
rp2_pie_abun3 <- aggregate(abun ~ genus + type, rp2_pie_abun2, FUN = "sum")

# phylum
#otu_all1_z1 <- as.data.frame(t(otu_all1_z[,rp1[rp1$type != "Stable",]$OTU.ID]))
otu_all1_z1 <- as.data.frame(t(otu_all1_z))
otu_all1_z1[] <- lapply(otu_all1_z1, as.numeric) 
otu_all1_z1$OTU.ID <- rownames(otu_all1_z1)

otu_id_with_traits <- readRDS("traits/otu_id_with_traits.rds")
otu_all1_z1 <- merge(otu_all1_z1, otu_id_with_traits, by="OTU.ID", stringsAsFactors = FALSE)


otu_all1_z2 <- aggregate(.~genus, otu_all1_z1[,c(2:486,503)], FUN = "sum")
otu_all1_z2 <- column_to_rownames(otu_all1_z2, "genus")

otu_all1_z2 <- as.data.frame(t(otu_all1_z2))
otu_all1_z2 <- otu_all1_z2[rownames(metadata),]


fit_data2 <- Maaslin2(
  input_data = otu_all1_z2,
  input_metadata = metadata,
  min_abundance = 0.001,
  min_prevalence = 0.01,
  min_variance = 0.0,
  output = "D:/Rtmp",
  normalization = "NONE",
  transform = "LOG",
  analysis_method = "LM",
  fixed_effects = c("ai2000"),
  random_effects = NULL,
  plot_scatter = FALSE
)

rp1_1 <- fit_data2$results
colnames(rp1_1)[1] = "otu"

rp1_1$type <- "none"
rp1_1[rp1_1$coef > 0.00 & rp1_1$qval <0.05,]$type <- "Up"
rp1_1[rp1_1$coef <= 0.00 & rp1_1$qval <0.05,]$type <- "Down"
rp1_1[rp1_1$qval >= 0.05,]$type <- "Stable"

abundance <- as.data.frame(colSums(otu_all1_z2))
names(abundance) <- "abu"
abundance$otu <- rownames(abundance)
abundance$abu <- (abundance$abu/sum(abundance$abu))*100
abundance <- abundance[order(abundance$abu, decreasing = T),]

select_phy <- abundance[order(abundance$abu, decreasing = T),"otu"][c(1:6,10,12,14:18,20:21)]
select_phy

sum(abundance$abu[c(1:6,10,12,14:18,20:21)])
sum(abundance$abu[c(1:20)])

rp1_1 <- left_join(rp1_1, abundance, by = "otu") 
rp1_2 <- rp1_1[rp1_1$otu %in% select_phy,]

#otu_id_with_traits <- separate(otu_id_with_traits, genus, sep = "_", into=c("pre_genus", "genus"))

gs <- aggregate(Assembly_Length~genus, otu_id_with_traits, FUN = "mean")

gs <- gs[gs$genus %in% select_phy,]
gs$label <- paste0(round(gs$Assembly_Length/1000000,2)," (Mb)")

gs <- left_join(gs, rp1_2, by=c("genus"="otu"))


diff_plot <- ggplot(rp1_2, aes(x=coef, y=factor(otu, levels = rev(c(select_phy))), size = abu, fill = factor(type, levels = c("Up","Down","Stable")))) +
  geom_point(shape=21) +
  geom_text(data = gs, aes(x=coef+0.5, y=genus, label =label), size=7.5, color="black") +
  scale_size_continuous(name="Phylum relative abundance (%)", range = c(3, 8)) +
  scale_fill_manual(name = "Phylum relative abundance", values = c("Down" = "#1445f8",
                                              "Up" = "#cd1936",
                                              "Stable" = "gray"),
                    labels =c("Up" = "Increase with aridity",
                              "Down" = "Decrease with aridity",
                              "Stable" = "Non-significant")) +
  guides(
    fill = guide_legend(
      override.aes = list(size = 4), order=1
    ),
    size = guide_legend(order = 2)
  ) +
  scale_x_continuous(breaks = c(-0.5, 0, 0.5, 1.0, 1.5), limits = c(-0.6,1.7)) +
  theme_bw() +
  labs(y="Top 15 genus", x="MassLin2 coefficient") +
  theme(axis.title.x = element_text(size=26),
        axis.text.x = element_text(size=22, color = "black"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(size=26),
        legend.text = element_text(size=22),
        legend.box.margin=margin(l=20)
  )

diff_plot


pie_df2 <- data.frame(
  "Phylum" = as.character(pie_df$OTU),
  "Up" = as.numeric(pie_df$Count.Up),
  "Down" = as.numeric(pie_df$Count.Down),
  "Stable" = as.numeric(pie_df$Count.Stable)
)

select_phy2 <- gsub("^g_", "", select_phy)
select_phy2

pie_df3 <- pie_df2[pie_df2$Phylum %in% select_phy2,]
rownames(pie_df3) <- pie_df3$Phylum
pie_df3 <- pie_df3[rev(select_phy2),]
pie_df3$x <- rep(1, nrow(pie_df3))  
pie_df3$y = 1:nrow(pie_df3)


pie_df3$all <- rowSums(pie_df3[,3:5])
# pie_df3$Phylum2 <- paste0(pie_df3$Phylum, " (n = ",pie_df3$all,")")

pie_df3$Phylum2 <- with(
  pie_df3,
  paste0("italic('", Phylum, "')~'(n = ", all, ")'")
)

pie_plot <- ggplot() +
  geom_scatterpie(data = pie_df3, aes(x = x, y = y, group=Phylum, r=0.4),
                  cols = c("Up", "Down", "Stable"), color = NA) +
  scale_fill_manual(name = "Accumulated OTU number", values = c("Down"="#2d9d56",
                                                                "Up"="#ff9d00",
                                                                "Stable"="gray"), 
                    labels =c("Up" = "Increase with aridity",
                              "Down" = "Decrease with aridity",
                              "Stable" = "Non-significant"))+
  scale_y_continuous(breaks = pie_df3$y,  labels = function(x) parse(text = pie_df3$Phylum2), expand = c(0.012, 0.012)) +
  coord_equal() +
  labs(y="Top 15 genus") +
  theme_void() +
  theme(axis.text.y = element_text(size=22, color = "black", hjust=1,  margin = margin(r = 10)),
        axis.title.y = element_text(size=26, angle = 90, margin = margin(r = 10)),
        legend.text = element_text(size=22),
        legend.title = element_text(size=26),
        legend.box.margin=margin(l=20)
  )

pie_plot

# pie abundance

rp2_pie_abun4 <- rp2_pie_abun3 %>%
  pivot_wider(
    names_from = type,
    values_from = abun
  )

pie_df2_abundance <- data.frame(
  "Phylum" = as.character(rp2_pie_abun4$genus),
  "Up" = as.numeric(rp2_pie_abun4$Up),
  "Down" = as.numeric(rp2_pie_abun4$Down),
  "Stable" = as.numeric(rp2_pie_abun4$Stable)
)

pie_df3_abundance <- pie_df2_abundance[pie_df2_abundance$Phylum %in% select_phy,]
rownames(pie_df3_abundance) <- pie_df3_abundance$Phylum
pie_df3_abundance <- pie_df3_abundance[rev(select_phy),]
pie_df3_abundance$x <- rep(1, nrow(pie_df3_abundance))  
pie_df3_abundance$y = 1:nrow(pie_df3_abundance)


pie_df3_abundance[is.na(pie_df3_abundance)] <- 0
pie_plot_abun <- ggplot() +
  geom_scatterpie(data = pie_df3_abundance, aes(x = x, y = y, group=Phylum, r=0.4),
                  cols = c("Up", "Down", "Stable"), color = NA) +
  scale_fill_manual(name = "OTU counts", values = c("Down"="#2d9d56",
                                                    "Up"="#ff9d00",
                                                    "Stable"="gray"), 
                    labels =c("Up" = "Increase",
                              "Down" = "Decrease",
                              "Stable" = "Non-significant"))+
  scale_y_continuous(breaks = pie_df3$y, labels = pie_df3$Phylum2, expand = c(0.012, 0.012)) +  # 设置 y 轴的标签为 Phylum
  coord_equal() +
  labs(y="Top 15 genus") +
  theme_void() +
  theme(axis.text.y = element_text(size=22, color = "black", hjust=1,  margin = margin(r = 10)),
        axis.title.y = element_text(size=26, angle = 90, margin = margin(r = 10)),
        legend.text = element_text(size=22),
        legend.title = element_text(size=26),
        legend.box.margin=margin(l=20) # 控制图例之间的距离
  )

pie_plot_abun

pie_plot_abun <- ggplot() +
  geom_scatterpie(data = pie_df3_abundance, aes(x = x, y = y, group=Phylum, r=0.4),
                  cols = c("Up", "Down", "Stable"), color = NA) +
  scale_fill_manual(name = "Accumulated OTU relative abundance", values = c("Down"="#9467BD",
                                                                            "Up"="chocolate",
                                                                            "Stable"="gray"), 
                    labels =c("Up" = "Increased with aridity",
                              "Down" = "Decrease with aridity",
                              "Stable" = "Non-significant"))+
  scale_y_continuous(breaks = pie_df3$y, labels = pie_df3$Phylum2, expand = c(0.012, 0.012)) +
  coord_equal() +
  labs(y="Top 15 genus") +
  theme_void() +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        legend.text = element_text(size=22),
        legend.title = element_text(size=26),
        legend.box.margin=margin(l=20)
  )

pie_plot_abun


p <- (pie_plot|plot_spacer()|pie_plot_abun|plot_spacer()|diff_plot) + plot_layout(guides = "collect",widths = c(1, -0.95, 1,-0.48,1)) +
  ggtitle("Fungi") +
  theme(plot.title = element_text(size=30, hjust = 0.5),
        legend.text = element_text(size=22),
        legend.title = element_text(size=26)
  )

print(p)
# 1830 700

```
