---
title: "Fig.1d-1e_Fungal genome size in field survey"
author: "Huanhuan Zhu"
date: "2025-09-19"
output: html_document
---


## Fig.1d_Fungal gnome size habitat comparison
```{r, fig.align='center', fig.height=4.6, fig.width=7.6, warning=FALSE, message=FALSE}

library(splitstackshape)
library(patchwork)
library(tibble)
library(reshape2)
library(ggpubr)
library(agricolae) # kruskal for nonparametric test
library(ggh4x)  # set individual y axis for facet
library(ggplot2)
library(tidyverse)
library(gghalves)
library(ggsignif)
library(rstatix)
library(data.table)
library(tidyr)
library(dplyr)

rm(list=ls())

setwd("E:/Functrait/Result/Fungi/otu2/")

metadata <- read.csv("metadata.csv")

otu_all0 <- read.csv("otu_fungFlattening_rrncor.csv",row.names = 1)
#otu_all0 <- otu_all0[rowSums(otu_all0) > 0, ]

table(colSums(otu_all0) >0 )


otu_all0 <- apply(otu_all0, 2, function(x) x / sum(x) * 100)
table(colSums(otu_all0))

otu_id <- read.csv("FUNTRAIT.fung.OTU.ID1.csv")
colnames(otu_id)[13:18] <- c("phylum", "class", "order", "family", "genus", "species")


# check NA data
table(is.na(otu_id$phylum))
table(is.na(otu_id$class))
table(is.na(otu_id$order))
table(is.na(otu_id$family))
table(is.na(otu_id$genus))
table(is.na(otu_id$species))

otu_id$phylum <- gsub("p__", "p_", otu_id$phylum)
otu_id$class <- gsub("c__", "c_", otu_id$class)
otu_id$order <- gsub("o__", "o_", otu_id$order)
otu_id$family <- gsub("f__", "f_", otu_id$family)
otu_id$genus <- gsub("g__", "g_", otu_id$genus)
otu_id$species <- gsub("s__", "s_", otu_id$species)


fungi_traits <- read.csv("traits/rCNV_rlt_taxa_spl_GSGN_new.csv")


metadata1_s <- aggregate(cbind(Assembly_Length, Both_ITS_LSU) ~ Name.y, fungi_traits, FUN = "mean")
metadata1_g <- aggregate(cbind(Assembly_Length, Both_ITS_LSU) ~ Gen, fungi_traits, FUN = "mean")
metadata1_f <- aggregate(cbind(Assembly_Length, Both_ITS_LSU) ~ fam, fungi_traits, FUN = "mean")
metadata1_o <- aggregate(cbind(Assembly_Length, Both_ITS_LSU) ~ ord, fungi_traits, FUN = "mean")
metadata1_c <- aggregate(cbind(Assembly_Length, Both_ITS_LSU) ~ cla, fungi_traits, FUN = "mean")
metadata1_p <- aggregate(cbind(Assembly_Length, Both_ITS_LSU) ~ phy, fungi_traits, FUN = "mean")

# add "level" column into metadata1
metadata1_s$level <- "species"
metadata1_g$level <- "genus"
metadata1_f$level <- "family"
metadata1_o$level <- "order"
metadata1_c$level <- "class"
metadata1_p$level <- "phylum"

colnames(metadata1_s)[1] <- "taxon"
colnames(metadata1_g)[1] <- "taxon"
colnames(metadata1_f)[1] <- "taxon"
colnames(metadata1_o)[1] <- "taxon"
colnames(metadata1_c)[1] <- "taxon"
colnames(metadata1_p)[1] <- "taxon"


metadata1_all <- bind_rows(metadata1_s, metadata1_g, metadata1_f,
                           metadata1_o, metadata1_c, metadata1_p)



otu_id$taxon_try <- ifelse(otu_id$species %in% metadata1_s$taxon, otu_id$species,
                          ifelse(otu_id$genus %in% metadata1_g$taxon, otu_id$genus,
                                 ifelse(otu_id$family %in% metadata1_f$taxon, otu_id$family,
                                        ifelse(otu_id$order %in% metadata1_o$taxon, otu_id$order,
                                               ifelse(otu_id$class %in% metadata1_c$taxon, otu_id$class,
                                                      ifelse(otu_id$phylum %in% metadata1_p$taxon, otu_id$phylum,
                                                                    NA))))))

otu_id_with_traits <- left_join(otu_id, metadata1_all, by = c("taxon_try" = "taxon"))
otu_id_with_traits[is.na(otu_id_with_traits$Both_ITS_LSU),]$Both_ITS_LSU = mean(fungi_traits[!is.na(fungi_traits$Both_ITS_LSU),]$Both_ITS_LSU)
otu_id_with_traits[is.na(otu_id_with_traits$Assembly_Length),]$Assembly_Length = mean(fungi_traits[!is.na(fungi_traits$Assembly_Length),]$Assembly_Length)

# saveRDS(otu_id_with_traits, "E:/Functrait/Result/Fungi/otu2/traits/otu_id_with_traits.rds")

#####################

otu_all_gs <- as.data.frame(otu_all0)
otu_all_gs$OTU.ID <- rownames(otu_all_gs)
otu_all_gs <- left_join(otu_all_gs, otu_id_with_traits[,c("OTU.ID","Assembly_Length")], by="OTU.ID")


otu_all_rrna <- as.data.frame(otu_all0)
otu_all_rrna$OTU.ID <- rownames(otu_all_rrna)
otu_all_rrna <- left_join(otu_all_rrna, otu_id_with_traits[,c("OTU.ID","Both_ITS_LSU")], by="OTU.ID")


otu_all_gs1 <- otu_all_gs
for (i in (1:(ncol(otu_all_gs1)-2))){
  otu_all_gs1[,i] <-  otu_all_gs1[,i] * otu_all_gs1[,ncol(otu_all_gs1)]/100000000
}

otu_all_gs2 <- as.data.frame(colSums(otu_all_gs1[,1:(ncol(otu_all_gs1) -2)]))
colnames(otu_all_gs2) <- "genome_size"
otu_all_gs2$runningSampleID <- rownames(otu_all_gs2)


otu_all_gs2 <- merge(otu_all_gs2, metadata, by="runningSampleID")
otu_all_gs2$ai2000 <- 1-1/otu_all_gs2$ai2000
otu_all_gs2$ai2022 <- 1-1/otu_all_gs2$ai2022

otu_all_gs2$type <- factor(otu_all_gs2$type,levels = c("Z", "B", "W"))

otu_all_gs2 <- otu_all_gs2[!(otu_all_gs2$site %in% sprintf("S%02d", 14)) ,]
otu_all_gs2$sampleType <- factor(otu_all_gs2$sampleType, levels=c('rhizosphere soil (Z)', 'bulk soil (B)', 'wild soil (W)'))

kruskal_res <- kruskal.test(genome_size/1000000 ~ sampleType, data = otu_all_gs2)

chi_sq <- round(kruskal_res$statistic, 2)   # 卡方
p_val  <- kruskal_res$p.value
df <- kruskal_res$parameter

#label_text <- bquote(chi^2 * "(" * "df = " * .(df) * ")" == .(format(chi_sq, format="g", digits=3)) * "," ~ italic(p) == .(formatC(p_val, format="e", digits=2)))
label_text <- sprintf("chi^2 * '(' * 'df = %d' * ')' == %g * ',' ~ italic(p) == %s", 
                      df, signif(chi_sq,3), formatC(p_val, format="e", digits=2))

# paired wilcox and p value adjust
res <- otu_all_gs2 %>%
  pairwise_wilcox_test(genome_size ~ sampleType, p.adjust.method = "fdr")

labels <- sprintf("italic(p) == '%s'", format(res$p.adj, scientific = TRUE, digits = 3))

set.seed(123)

p <- ggplot(otu_all_gs2, aes(x=sampleType, y=genome_size)) +
  geom_half_violin(side = "r", aes(fill = sampleType), color=NA, alpha=0.6, position = position_dodge(width = 0.8)) +
  geom_half_boxplot(side = "r", errorbar.draw = FALSE, width=0.2, linewidth=0.5, 
                    position = position_dodge(width = 0.8), outlier.size = 0.8, outlier.alpha = 0.6, alpha=0.6) +
  # geom_half_point_panel(side = "l", aes(color = sampleType),shape=21, size=0.1, alpha = 0.6, range_scale = 0.5,
  #                       position = position_dodge(width = 0.8)) +
  geom_jitter(aes(x = as.numeric(factor(sampleType)) - 0.15, color = sampleType), 
              shape = 21, size=0.1, alpha = 0.6, width = 0.05) +
  scale_x_discrete(
                    labels = c(
                      'bulk soil (B)' = "Maizeland\nbulk soil",
                      'rhizosphere soil (Z)' = "Maize\nrhizosphere",
                      'wild soil (W)' = "Wildland\nsoil"
  )) +
  scale_y_continuous(labels = scales::number_format(accuracy = 1),limits = c(30,310)) +
  scale_fill_manual(name = "Type", 
                    values = rev(c("#cd1936","#40b3b3","#1445f8")), 
                    labels = c(
                      'bulk soil (B)' = "Maizeland\nbulk soil",
                      'rhizosphere soil (Z)' = "Maize\nrhizosphere",
                      'wild soil (W)' = "Wildland\nsoil"
                    )) +
  scale_color_manual(name = "Type", 
                     values = rev(c("#cd1936","#40b3b3","#1445f8")), 
                     labels = c(
                       'bulk soil (B)' = "Maizeland\nbulk soil",
                       'rhizosphere soil (Z)' = "Maize\nrhizosphere",
                       'wild soil (W)' = "Wildland\nsoil"
                     )) +
  labs(x ="Sample type", title = "Fungi", y="CWM genome size (Mb)") +
  ggplot2::annotate("text", x = "rhizosphere soil (Z)", y = 300, label = label_text, size = 8, hjust = 0.18, parse = TRUE) +
  geom_signif(data = res, aes(y_position = c(165, 240, 200), 
                              xmin = group1, 
                              xmax = group2, 
                              annotations = labels, tip_length = 0.02),
              manual = TRUE, textsize = 8, parse = T)+
  theme_bw() +
  theme(plot.title = element_text(color = "black", size = 30, hjust = 0.5),
        axis.title = element_text(color = "black", size = 26), 
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text = element_text(color = "black", size = 22),
        legend.title = element_text(color = "black", size = 26, vjust=2),
        legend.text = element_text(color = "black", size = 22),
        legend.key.spacing.y = unit(0.5,"cm"),
        strip.text = element_text(color = "black",size = 22),
        strip.background =element_rect(fill="lightgrey", size = 0)
  )

print(p)

```



## Fig.1e_Fungal genome size aridity correlation
```{r, fig.align='center', fig.height=5, fig.width=7.5, warning=FALSE, message=FALSE}

cor_res <- otu_all_gs2 %>%
  group_by(sampleType) %>%
  summarise(
    cor_test = list(cor.test(genome_size/1000000, 1-1/ai2000, method = "spearman")),
    .groups = "drop"
  ) %>%
  mutate(
    rho = sapply(cor_test, function(x) x$estimate),
    p_val = sapply(cor_test, function(x) x$p.value))

labels2 <- sprintf("rho == '%s' * ',' ~ italic(p) == '%s'", round(cor_res$rho, 3), format(cor_res$p_val, scientific = TRUE, digits = 3))

p1_all <- ggplot(otu_all_gs2, aes(x=ai2000, y=genome_size,color = factor(sampleType), group = factor(sampleType))) +
  geom_point(size=2, alpha=0.3)+
  geom_smooth(aes(color = factor(sampleType)), method = 'lm', formula = "y~x", se = F, level = 0.95, linewidth = 3, alpha = 0.4) +
  geom_text(data = cor_res, aes(x = 0.79,
                                y = c(162, 145.5, 129),
                                label = labels2,
                                color = sampleType),
            inherit.aes = FALSE, hjust = 0, size = 8, parse = TRUE, show.legend = FALSE) +
  scale_color_manual(name="Type",values = rev(c("#cd1936","#40b3b3","#1445f8")),labels =c(
    'bulk soil (B)' = "Maizeland\nbulk soil",
    'rhizosphere soil (Z)' = "Maize\nrhizosphere",
    'wild soil (W)' = "Wildland\nsoil"
  )) +
  labs(x="Wetter   ←   Aridity   →   Drier", y="CWM genome size (Mb)", title="Fungi") +
  theme_bw() +
  theme(plot.title = element_text(color = "black", size = 30, hjust = 0.5),
        axis.title = element_text(color = "black", size = 26), 
        #axis.title.x = element_blank(),
        axis.text = element_text(color = "black", size = 22),
        legend.title = element_text(color = "black", size = 26, vjust=2),
        legend.text = element_text(color = "black", size = 22),
        legend.key.spacing.y = unit(0.5,"cm"),
        strip.text = element_text(color = "black",size = 22),
        strip.background =element_rect(fill="lightgrey", size = 0)
  )

print(p1_all)

```

