---
title: "Fig.1b-1c_Prokaryotic genome size in field survey"
author: "Huanhuan Zhu"
date: "2025-09-19"
output: html_document
---


## Fig.1b_Prokaryotic genome size habitat comparison
```{r, fig.align='center', fig.height=4.6, fig.width=7.6, warning=FALSE, message=FALSE}

library(splitstackshape)
library(patchwork)
library(tibble)
library(reshape2)
library(ggpubr)
library(agricolae) # kruskal for nonparametric test
library(ggh4x)  # set individual y axis for facet
library(ggplot2)
library(tidyverse)
library(gghalves)
library(ggsignif)
library(rstatix)
library(data.table)
library(tidyr)
library(dplyr)

rm(list=ls())

setwd("E:/Functrait/Result/Bacteria/otu2/gtdb/")

# read result blast
blast <- read.csv("qiime2/taxonomy.tsv", sep = "\t")  
blast <- blast[!duplicated(blast$Feature.ID),]
blast <- blast %>% separate(Taxon, c("domain","phylum","class","order","family","genus","species"), sep = ";")

# read metadata of GTDB
# metadata_bac <- as.data.frame(fread("D:/database/gtdb/bac120_metadata_r226.tsv"))
# metadata_arc <- as.data.frame(fread("D:/database/gtdb/ar53_metadata_r226.tsv"))
# metadata <- rbind(metadata_bac,metadata_arc)
# saveRDS(metadata,"E:/Functrait/code2-new/metadata_functraits.RDS")
metadata <- readRDS("E:/Functrait/code2-new/metadata_functraits.RDS")
metadata1 <- metadata[,c("gtdb_taxonomy","genome_size","gc_percentage")]
metadata1 <- metadata1 %>% separate(gtdb_taxonomy, c("domain","phylum","class","order","family","genus","species"), sep = ";")

metadata1_s <- aggregate(cbind(genome_size, gc_percentage) ~ species, metadata1, FUN = "mean")
metadata1_g <- aggregate(cbind(genome_size, gc_percentage) ~ genus, metadata1, FUN = "mean")
metadata1_f <- aggregate(cbind(genome_size, gc_percentage) ~ family, metadata1, FUN = "mean")
metadata1_o <- aggregate(cbind(genome_size, gc_percentage) ~ order, metadata1, FUN = "mean")
metadata1_c <- aggregate(cbind(genome_size, gc_percentage) ~ class, metadata1, FUN = "mean")
metadata1_p <- aggregate(cbind(genome_size, gc_percentage) ~ phylum, metadata1, FUN = "mean")
metadata1_d <- aggregate(cbind(genome_size, gc_percentage) ~ domain, metadata1, FUN = "mean")

metadata1_s$level <- "species"
metadata1_g$level <- "genus"
metadata1_f$level <- "family"
metadata1_o$level <- "order"
metadata1_c$level <- "class"
metadata1_p$level <- "phylum"
metadata1_d$level <- "domain"

colnames(metadata1_s)[1] <- "taxon"
colnames(metadata1_g)[1] <- "taxon"
colnames(metadata1_f)[1] <- "taxon"
colnames(metadata1_o)[1] <- "taxon"
colnames(metadata1_c)[1] <- "taxon"
colnames(metadata1_p)[1] <- "taxon"
colnames(metadata1_d)[1] <- "taxon"

metadata1_all <- bind_rows(metadata1_s, metadata1_g, metadata1_f,
                              metadata1_o, metadata1_c, metadata1_p, metadata1_d)


blast$taxon_try <- ifelse(blast$species %in% metadata1_s$taxon, blast$species,
                          ifelse(blast$genus %in% metadata1_g$taxon, blast$genus,
                                 ifelse(blast$family %in% metadata1_f$taxon, blast$family,
                                        ifelse(blast$order %in% metadata1_o$taxon, blast$order,
                                               ifelse(blast$class %in% metadata1_c$taxon, blast$class,
                                                      ifelse(blast$phylum %in% metadata1_p$taxon, blast$phylum,
                                                             ifelse(blast$domain %in% metadata1_d$taxon, blast$domain,
                                                                    NA)))))))

blast_with_traits <- left_join(blast, metadata1_all, by = c("taxon_try" = "taxon"))


table(is.na(blast_with_traits$genome_size))
table(is.na(blast_with_traits$gc_percentage))


# read rarefied otu table
otu_table <- as.data.frame(fread("../otu_bacteriaFlattening_rrncor.csv"))
otu_table1 <- otu_table %>% separate(V1, into = c("First", "Second"), "[.]")

otu_table2 <- merge(otu_table1,blast_with_traits[,c("Feature.ID","genome_size","gc_percentage")],by.x = "First",by.y = "Feature.ID")
#saveRDS(blast_with_traits,"E:/Functrait/Result/Bacteria/otu2/gtdb/blast_gtdb.RDS")

# otu_table2[is.na(otu_table2$genome_size),]$genome_size <- mean(otu_table2[!is.na(otu_table2$genome_size),]$genome_size) 
#The unassigned was defined to mean value (same results with remove unassigned)

table(is.na(otu_table2$genome_size))
otu_table2 <- otu_table2[!is.na(otu_table2$genome_size),]  # remove unassigned

colnames(otu_table2)[1946]

# min(colSums(otu_table2[,3:1946]))
# mean(colSums(otu_table2[,3:1946]))
# max(colSums(otu_table2[,3:1946]))

colnames(otu_table2)[1946]
#2045 1800

### 1 calculate avergae genome size 
my_gs <- function(name){
  
  otu_table3 <- otu_table2
  otu_table3[,3:1946] <- apply(otu_table3[,3:1946],2,function(x) x/sum(x))  # percentage by column
  colSums(otu_table3[,3:1946])  # check if the sum of each column is equal to 1
  
  # average genome size
  for(i in 3:1946){  
    otu_table3[,i] <- otu_table3[,i]*otu_table3[,name]
  }
  
  genomesize_ave <- as.data.frame(colSums(otu_table3[,3:1946]))
  
  genomesize_ave3 <- genomesize_ave
  genomesize_ave3$sample.id <- rownames(genomesize_ave3)
  names(genomesize_ave3)[1] <- "genome_size"
  genomesize_ave3 <<- genomesize_ave3
}

my_gs("genome_size")


group <- read.csv("E:/Functrait/Result/metadata/metadata.csv")

genomesize_ave3 <- merge(genomesize_ave3, group, by.x="sample.id", by.y="runningSampleID")

ai2000_site <- aggregate(ai2000~site,genomesize_ave3,FUN = "mean")
ai2000_site$ai2000 <- (1/ai2000_site$ai2000)

set.seed(123) 
k_clusters <- kmeans(ai2000_site$ai2000, centers = 3)

ai2000_site$Cluster <- as.factor(k_clusters$cluster)
ai2000_site <- ai2000_site[,c(1,3)]

# print(ai2000_site)

genomesize_ave3 <- merge(genomesize_ave3, ai2000_site, by="site")


genomesize_ave4 <- genomesize_ave3[!(genomesize_ave3$site %in% sprintf("S%02d", 14)) ,]
genomesize_ave4$sampleType <- factor(genomesize_ave4$sampleType, levels=c('rhizosphere soil (Z)', 'bulk soil (B)', 'wild soil (W)'))


kruskal_res <- kruskal.test(genome_size/1000000 ~ sampleType, data = genomesize_ave4)

chi_sq <- round(kruskal_res$statistic, 2)
p_val  <- kruskal_res$p.value
df <- kruskal_res$parameter

#label_text <- bquote(chi^2 * "(" * "df = " * .(df) * ")" == .(format(chi_sq, format="g", digits=3)) * "," ~ italic(p) == .(formatC(p_val, format="e", digits=2)))
label_text <- sprintf("chi^2 * '(' * 'df = %d' * ')' == %g * ',' ~ italic(p) == %s", 
                      df, signif(chi_sq,3), formatC(p_val, format="e", digits=2))

# paired wilcox and p value adjust
res <- genomesize_ave4 %>%
  pairwise_wilcox_test(genome_size ~ sampleType, p.adjust.method = "fdr")


labels <- sprintf("italic(p) == '%s'", format(res$p.adj, scientific = TRUE, digits = 3))

set.seed(123) 
# Fig.1c_Prokaryotic gs comparison
p <- ggplot(genomesize_ave4, aes(x=sampleType, y=genome_size/1000000)) +
  geom_half_violin(side = "r", aes(fill = sampleType), color=NA, alpha=0.6, position = position_dodge(width = 0.8)) +
  geom_half_boxplot(side = "r", errorbar.draw = FALSE, width=0.2, linewidth=0.5, 
                    position = position_dodge(width = 0.8), outlier.size = 0.8, outlier.alpha = 0.6) +
  # geom_half_point_panel(side = "l", aes(color = sampleType),shape=21, size=0.1, alpha = 0.6, range_scale = 0.5,
  #                       position = position_dodge(width = 0.8)) +
  geom_jitter(aes(x = as.numeric(factor(sampleType)) - 0.15, color = sampleType), 
              shape = 21, size=0.1, alpha = 0.6, width = 0.05) +
  scale_x_discrete(labels = c(
    'bulk soil (B)' = "Bulk",
    'rhizosphere soil (Z)' = "Rhizosphere",
    'wild soil (W)' = "Wild"
  )) +
  scale_y_continuous(labels = scales::number_format(accuracy = 0.1), limits = c(3.3, 7.1)) +
  scale_fill_manual(name = "Type", 
                    values = rev(c("#cd1936","#40b3b3","#1445f8")), 
                    labels = c(
                      'bulk soil (B)' = "Maizebulk",
                      'rhizosphere soil (Z)' = "Rhizosphere",
                      'wild soil (W)' = "Wildland"
                    )) +
  scale_color_manual(name = "Type", 
                     values = rev(c("#cd1936","#40b3b3","#1445f8")), 
                     labels = c(
                       'bulk soil (B)' = "Maizebulk",
                       'rhizosphere soil (Z)' = "Rhizosphere",
                       'wild soil (W)' = "Wildland"
                     )) +
  labs(x ="Sample type", title = "Prokaryotes", y="CWM genome size (Mb)") +
  ggplot2::annotate("text", x = "rhizosphere soil (Z)", y = 7, label = label_text, size = 8, hjust = 0.18, parse = TRUE) +
  geom_signif(data = res, aes(y_position = c(5.1, 6.2, 5.65), 
                              xmin = group1, 
                              xmax = group2, 
                              annotations = labels, tip_length = 0.02),
    manual = TRUE, textsize = 8, parse = T)+
  theme_bw() +
  theme(plot.title = element_text(color = "black", size = 30, hjust = 0.5),
        axis.title = element_text(color = "black", size = 26), 
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text = element_text(color = "black", size = 22),
        legend.title = element_text(color = "black", size = 26),
        legend.text = element_text(color = "black", size = 22),
        strip.text = element_text(color = "black",size = 22),
        strip.background =element_rect(fill="lightgrey", size = 0)
  )

print(p)

```



## Fig.1b_Prokaryotic genome size aridity correlation
```{r, fig.align='center', fig.height=5, fig.width=7.5, warning=FALSE, message=FALSE}

cor_res <- genomesize_ave4 %>%
  group_by(sampleType) %>%
  summarise(
    cor_test = list(cor.test(genome_size/1000000, 1-1/ai2000, method = "spearman")),
    .groups = "drop"
  ) %>%
  mutate(
    rho = sapply(cor_test, function(x) x$estimate),
    p_val = sapply(cor_test, function(x) x$p.value))


labels2 <- sprintf("rho == '%s' * ',' ~ italic(p) == '%s'", round(cor_res$rho, 3), format(cor_res$p_val, scientific = TRUE, digits = 3))
labels2[3] = "rho == '0.136' * ',' ~ italic(p) == '0.00157'"


p <- ggplot(genomesize_ave4, aes(x = (1-1/ai2000), y = genome_size/1000000, color = sampleType)) +
  geom_point(size=2, alpha=0.3)+
  geom_smooth(aes(color = factor(sampleType)), method = 'lm', formula = "y~x", se = F, level = 0.95, linewidth = 3) +
  geom_text(data = cor_res, aes(x = 0.75,
                                y = c(5.2, 4.97, 4.74),
                                label = labels2,
                                color = sampleType),
            inherit.aes = FALSE, hjust = 0, size = 8, parse = TRUE, show.legend = FALSE) +
  scale_color_manual(name="Type",values = rev(c("#cd1936","#40b3b3","#1445f8")),labels =c(
    'bulk soil (B)' = "Maizeland\nbulk soil",
    'rhizosphere soil (Z)' = "Maize\nrhizosphere",
    'wild soil (W)' = "Wildland\nsoil"
  )) +
  labs(x="Wetter   ←   Aridity   →   Drier", y="CWM genome size (Mb)", title="Prokaryotes") +
  # stat_cor(aes(color = factor(sampleType)), label.y.npc="top", label.x.npc = "left", 
  #          method = "spearman",size=8, show.legend = FALSE) +
  theme_bw() +
  theme(plot.title = element_text(color = "black", size = 30, hjust = 0.5),
        axis.title = element_text(color = "black", size = 26), 
        #axis.title.x = element_blank(),
        axis.text = element_text(color = "black", size = 22),
        legend.title = element_text(color = "black", size = 26, vjust=2),
        legend.text = element_text(color = "black", size = 22),
        legend.key.spacing.y = unit(0.5,"cm"),
        strip.text = element_text(color = "black",size = 22),
        strip.background =element_rect(fill="lightgrey", size = 0)
  )

print(p)

```

