---
title: "Fig.S3a & Fig.S3b_Maaslin2"
author: "Huanhuan Zhu"
date: "2025-12-12"
output: html_document
---

## Baciluus
```{r, fig.align='center', fig.height=5.2, fig.width=10, warning=FALSE, message=FALSE}
library(data.table)
library(tibble)
library(dplyr)
library(tidyr)
library(ggplot2)
library(Maaslin2)
# bacteria
setwd("E:/HMME/Amplicon/4-data analysis/amplicon(zhh)/Result/Bacteria/otu2/")

rm(list = ls())

otu_all0 <- as.data.frame(fread("otu_bacteriaFlattening_rrncor.csv"))
otu_all0 <- column_to_rownames(otu_all0,"V1")
otu_all0 <- as.data.frame(t(otu_all0))


otu_all1_z <- otu_all0[grepl("TS", rownames(otu_all0)),]

metadata <-data.frame("id" = rownames(otu_all1_z), "group" = as.numeric(substr(rownames(otu_all1_z),1,1))) 
metadata <- column_to_rownames(metadata,"id")


fit_data <- Maaslin2(
  input_data = otu_all1_z,
  input_metadata = metadata,
  min_abundance = 0,
  min_prevalence = 0.1,
  min_variance = 0.0,
  output = "D:/Rtmp",
  normalization = "none",
  transform = "LOG",
  analysis_method = "LM",
  cores = 1,
  fixed_effects = c("group"),
  random_effects = NULL,
  plot_scatter = FALSE
)


rp1 <- fit_data$results

colnames(rp1)[1] = "otu"
rp1 <- separate(rp1,"otu", sep = "\\.", into = "otu")


rp1$type <- "none"
rp1[rp1$coef > 0.00 & rp1$qval <0.05,]$type <- "Up"
rp1[rp1$coef <= 0.00 & rp1$qval <0.05,]$type <- "Down"
rp1[rp1$qval >= 0.05,]$type <- "Stable"

############

group <- read.csv("HMME.bact.OTU.ID1.csv")

rp1 <- left_join(rp1, group, by=c("otu"="V1"))


df <- rp1


df$label <- paste(df$otu, df$V5_06, sep = "_")
df[is.na(df)] <- "_"

df[abs(df$coef) < 1, ]$label = ""
df[df$V5_06 =="Incertae Sedis",]$label = ""
df[grepl("uncultured",df$V5_07),]$label = ""
df[grepl("metagenome",df$V5_07),]$label = ""

df$type2 = "none"
df[df$label != "",]$type2 = "label"


otu_all1_z6 <- otu_all1_z[grepl("6TS",rownames(otu_all1_z)),]
otu_all1_z6 <- data.frame("id" = names(colMeans(otu_all1_z6)), counts = as.numeric(colMeans(otu_all1_z6)))
otu_all1_z6$abundance <- (otu_all1_z6$counts/sum(otu_all1_z6$counts))*100

df2 <- left_join(df, otu_all1_z6, by=c("OTU.ID"="id"))
df2 <- df2[df2$coef > 0 & df2$qval <0.05, ]

df2$label2 <- ""
df2[df2$coef > 1 & df2$abundance > 2, ]$label2 <- df2[df2$coef > 1 & df2$abundance > 2, ]$OTU.ID

colors <- c(
"#FFA500", "#8bc24c", "#FFD700", "#2196F3", "#8A4B08",
"#FF7F00", "#d9534f", "#86519D", "#1B9E77", "#EE4C97",
"#3B3B98", "#2B5A41", "#E41A1C", "#b4bb72", "#b23256",
"#377EB8", "#4DAF4A", "#984EA3", "#B22222", "#A65628",
"#F781BF", "#666666", "#D95F02", "#6495ED", "#E7298A"
)



# bacillus

p <- ggplot(df2[df2$V5_02 == "Bacillota", ], aes(x = coef, y = abundance, color = factor(V5_06))) +
  geom_point(alpha = 1, aes(size = -log(qval))) +
  # geom_vline(xintercept = 1, linetype = "dashed", color = "darkgray", size = 0.5)+
  # geom_hline(yintercept = 2, linetype = "dashed", color = "darkgray", size = 0.5)+
  scale_colour_manual(name = "Phylum", values = c("Metabacillus" = "#FF7F00",
                                                  "Lysinibacillus" = "#86519D",
                                                  "Oxalophagus" = "#2196F3",
                                                  "Neobacillus" = "#E41A1C", # red
                                                  "Paenibacillus" = "#b4bb72"),
                      labels = c("Metabacillus" = "Metabacillus (OTU_173)",
                                 "Lysinibacillus" = "Lysinibacillus (OTU_167)",
                                 "Oxalophagus" = "Oxalophagus (OTU_97)",
                                 "Neobacillus" = "Neobacillus (OTU_3)", # red
                                 "Paenibacillus" = "Paenibacillus (OTU_49)")) +
  scale_size_continuous(name="-Log(adjusted P value)", range = c(2, 8)) +
  labs(x = "Maaslin2 coefficient", y = "Relative abundance\nin final generation (%)", title = "Enriched Bacillota OTUs") +
  guides(
    color = guide_legend(
      override.aes = list(size = 4)
    )) +
  theme_bw() +
  theme(plot.title = element_text(color = "black", size = 30, hjust = 0.5),
        #axis.title.x = element_text(color = "black", size = 16), 
        axis.title = element_text(color = "black", size = 26), 
        axis.text.y = element_text(color = "black", size = 22),
        axis.text.x = element_text(color = "black", size = 22),
        legend.title = element_text(color = "black", size = 26),
        legend.text = element_text(color = "black", size = 22),
        legend.key.spacing.y = unit(0.1,"cm"), 
        strip.text = element_text(color = "black",size = 22),
        strip.background =element_rect(fill="lightgrey", size = 0)
  )

print(p)

# 10 5.2 

```


## Fungi
```{r, fig.align='center', fig.height=5, fig.width=8, warning=FALSE, message=FALSE}

setwd("E:/HMME/Amplicon/4-data analysis/amplicon(zhh)/Result/Fungi/otu2/")

rm(list = ls())

otu_all0 <- as.data.frame(fread("otu_fungFlattening_rrncor.csv"))
otu_all0 <- column_to_rownames(otu_all0,"V1")
otu_all0 <- as.data.frame(t(otu_all0))


otu_all1_z <- otu_all0[grepl("TS", rownames(otu_all0)),]

metadata <-data.frame("id" = rownames(otu_all1_z), "group" = as.numeric(substr(rownames(otu_all1_z),1,1))) 
metadata <- column_to_rownames(metadata,"id")


fit_data <- Maaslin2(
  input_data = otu_all1_z,
  input_metadata = metadata,
  min_abundance = 0.001,
  min_prevalence = 0.01,
  min_variance = 0.0,
  output = "D:/Rtmp", 
  normalization = "none",
  transform = "LOG", 
  analysis_method = "LM",
  cores = 1,
  fixed_effects = c("group"),
  random_effects = NULL,
  plot_scatter = FALSE
)


rp1 <- fit_data$results

colnames(rp1)[1] = "otu"



rp1$type <- "none"
rp1[rp1$coef > 0.00 & rp1$qval <0.05,]$type <- "Up"
rp1[rp1$coef <= 0.00 & rp1$qval <0.05,]$type <- "Down"
rp1[rp1$qval >= 0.05,]$type <- "Stable"

############

group <- read.csv("HMME.fung.OTU.ID1.csv")

rp1 <- left_join(rp1, group, by=c("otu"="OTU.ID"))
rp1 <- separate(rp1,V5_6, sep = "__", into = c("pre_V5_6", "V5_6"))
rp1 <- separate(rp1,V5_6, sep = "_", into = c("V5_6"))
rp1 <- separate(rp1,V5_2, sep = "__", into = c("pre_V5_2", "V5_2"))


df <- rp1

df$label <- paste(df$V1, df$V5_6, sep = "_")
df[is.na(df)] <- "_"

df[abs(df$coef) < 0.8, ]$label = ""

df$type2 = "none"
df[df$label != "",]$type2 = "label"

otu_all1_z6 <- otu_all1_z[grepl("6TS",rownames(otu_all1_z)),]
otu_all1_z6 <- data.frame("id" = names(colMeans(otu_all1_z6)), counts = as.numeric(colMeans(otu_all1_z6)))
otu_all1_z6$abundance <- (otu_all1_z6$counts/sum(otu_all1_z6$counts))*100

df2 <- left_join(df, otu_all1_z6, by=c("otu"="id"))
df2 <- df2[df2$coef > 0 & df2$qval <0.05, ]

df2$label2 <- ""
df2[df2$coef > 0.8 & df2$abundance > 5, ]$label2 <- paste0(df2[df2$coef > 0.8 & df2$abundance > 5, ]$V1, "_", df2[df2$coef > 0.8 & df2$abundance > 5, ]$V5_6)


colors <- c(
  "#E41A1C", # red
  "#377EB8", # blue
  "#4DAF4A", # green
  "#984EA3", # purple
  "#FFFF33", # yellow
  "#F781BF", # pink
  "#666666", # gray
  "#D95F02", # deep orange
  "#6495ED", # muted blue
  "#66A61E", # olive green
  "#FF7F00", # orange #
  "#A65628", # dark brown #
  "#1B9E77", # dark teal #
  "#E7298A" # deep pink #
  #"#A6761D", # dark mustard #
)



p <- ggplot(df2, aes(x = coef, y = abundance, color = factor(V5_6, levels = rev(c("Talaromyces", "Trichoderma", "Humicola", "Rhodotorula","Naganishia", "Lecythophora", 
                                                                             "Papiliotrema", "Tremellales", "Cystobasidium", "Solicoccozyma", "Simplicillium", 
                                                                             "Exophiala", "Penicillium", "Mucor"))))) +
  geom_point(alpha = 1, size = 3) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "darkgray", size = 0.5)+
  geom_hline(yintercept = 5, linetype = "dashed", color = "darkgray", size = 0.5)+
  scale_colour_manual(name = "Genus", values = rev(colors)) +
  labs(x = "Maaslin2 coefficient", y = "Relative abundance\nin final generation (%)", title = "Enriched fungal OTUs") +
  theme_bw() +
  theme(plot.title = element_text(color = "black", size = 30, hjust = 0.5),
        #axis.title.x = element_text(color = "black", size = 16), 
        axis.title = element_text(color = "black", size = 26), 
        axis.text.y = element_text(color = "black", size = 22),
        axis.text.x = element_text(color = "black", size = 22),
        legend.title = element_text(color = "black", size = 24),
        legend.text = element_text(color = "black", size = 20, face = "italic"),
        strip.text = element_text(color = "black",size = 22),
        strip.background =element_rect(fill="lightgrey", size = 0)
  ) +
  ggrepel::geom_text_repel(
    data = df2,
    aes(label = label2),
    color = "black",
    size = 8,
    force = 2,
    max.overlaps = Inf,
    box.padding = 0.8,
    point.padding = 0.5,
    segment.color = "darkgrey",
    segment.size = 0.4,
    show.legend = FALSE
  )


print(p)
# 8 5

```
